### ISSUE TITLE
Possible Vulnerability/Bug

### ISSUE THREAD

**Issue by splitbrain** [Taggic/removeold#3]
A static scan of this plugin revealed that the plugin is outputting data from $_REQUEST unfiltered and unescaped. This could lead to a potential XSS vulnerability or break functionality with unexpected input.

See http://php-grinder.com/project/view/19139 for the scan results

**Comment by TP75** [comment]
There seems to be an issue refering to the _inc/Plugin.php_ (capital P) and _inc/plugin.php_ since the _Release 2018-04-22 "Greebo"_ dokuwiki upgrade.

Please have a look at the discussion in the [DokuWiki Forum 60569: After upgrade to Greebo, failed to open stream](https://forum.dokuwiki.org/post/60569).
